### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by michaelkole** [nborrmann/jodel_api#15]
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    j = jodel_api.JodelAccount(lat=lat, lng=lng, city=city)
  File "C:\Python\lib\site-packages\jodel_api.py", line 49, in __init__
    r = self.refresh_all_tokens(**kwargs)
  File "C:\Python\lib\site-packages\jodel_api.py", line 117, in refresh_all_tokens
    raise Exception(resp)
Exception: (477, 'Signed request expected')

**Comment by nborrmann** [comment]
What version are you on? Make sure to update.

**Comment by michaelkole** [comment]
Hello,

first of all thank you for the API.
I cannot create an account via your program. As soon as I try to create an
account the error 477 appears.
With following saying:
Creating new account.
Traceback (most recent call last):
  File "C:\Python\Jodel\Progs\Automatisierungs_Prog\create_acc.py", line 8,
in <module>
    j = jodel_api.JodelAccount(lat=lat, lng=lng, city=city)
  File "C:\Python\lib\site-packages\jodel_api.py", line 49, in __init__
    r = self.refresh_all_tokens(**kwargs)
  File "C:\Python\lib\site-packages\jodel_api.py", line 117, in
refresh_all_tokens
    raise Exception(resp)
Exception: (477, 'Signed request expected')
>>>

2017-04-16 20:15 GMT+02:00 nbo <notifications@github.com>:

**Comment by michaelkole** [comment]
version = '4.41.0'

2017-04-17 16:28 GMT+02:00 nbo <notifications@github.com>:

**Comment by nborrmann** [comment]
4.41 should be working.

Please run `pip show jodel_api` and paste the output here.

**Comment by michaelkole** [comment]
Name: jodel-api
Version: 1.1.0
Summary: Unoffical Python Interface to the Jodel API Edit
Home-page: https://github.com/nborrmann/jodel_api
Author: Nils Borrmann
Author-email: n.borrmann@googlemail.com
License: MIT
Location: c:\python\lib\site-packages
Requires: mock, requests, future


Oh I see now that I did not update it. I am very sorry

2017-04-17 17:20 GMT+02:00 nbo <notifications@github.com>:
