### ISSUE TITLE
Signing key changed?

### ISSUE THREAD

**Issue by Patralos** [nborrmann/jodel_api#40]
It seems like the signing key has been changed:
>>> import jodel_api
>>> lat, lng, city = 48.148434, 11.567867, "Munich"
>>> j = jodel_api.JodelAccount(lat=lat, lng=lng, city=city)
Creating new account.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/jodel_api-1.2.5-py2.7.egg/jodel_api/jodel_api.py", line 56, in __init__
    r = self.refresh_all_tokens(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jodel_api-1.2.5-py2.7.egg/jodel_api/jodel_api.py", line 136, in refresh_all_tokens
    raise Exception(resp)
Exception: (477, {u'metadata': None, u'error': u'Signed request expected'})
## Environment

4.49.0
GnAXvETHFDbDfhngjDYEkszdqZowDpWsWuCectMJ

**Comment by mullanptr** [comment]
Have the same problem.
According to the [error-codes](https://github.com/nborrmann/jodel_api#error-codes)
this will be fixed if the jodel_api is getting a new release.
So we simply might just have to wait.

**Comment by espilsad** [comment]
You can do it yourself with this tool:
https://github.com/nborrmann/jodeldecompile

**Comment by tom-eagle92** [comment]
Was anybody able to get the new signing key? 
I can't get the scripts from the jdoeldecompile repository working, same with the ojoc-keyhack scripts.

**Comment by gaurav-stepin** [comment]
Hi mate,
I just wanted to check that if you are going to update api-key soon?
thanks

**Comment by Thamos** [comment]
Here are the last few keys (there's also a pull request for the newest)

version: 4.55.1
secret: SUJlYgihNxTmcfdrEcjROozfNemiqJSjYpoJJMUC
version: 4.54.1
secret: lYgeNFRCzBYVxqVtxeaJAHHZnogGssMFgVTgxBvP
version: 4.53.1
secret: UJBCWDUHEtpdiawcSEJSpUSXtWbrXOfIWeYTRVjX

**Comment by Gudui** [comment]
@Thamos 

How do you extract the keys?

I've look at https://github.com/nborrmann/jodeldecompile/
But im stuck in the fourth step, where a decompiler is used, but i can't seem to find the specific decompiler.

Thanks in advance

**Comment by kian1991** [comment]
@Thamos would you please delete the keys? It's okay if only ones with the knowledge to extract it have them. The more spammer and abuser out there the more likely it won't be possible to use their API in the future! (And there are a lot of guys abusing it unfortunately)

**Comment by Thamos** [comment]
@Gudui
Just google for a .so decompiler, I'm sure you can find one. 

@kian1991
Since 4.56.1 is already released I won't remove them (cause they are soon invalid anyway). However I won't post the new key.

**Comment by Gudui** [comment]
@Thamos 
Thanks for the tip, i'll try then :-).

**Comment by Daedra223** [comment]
@Gudui would you please post the key for 4.57.1, because the aim of github is not to hide knowledge as @kian1991 wants to do it, its about sharing knowledge ...

**Comment by Daedra223** [comment]
@Guidui and @kian1991 true please delete all keys and avoid spamming and missusing ...

**Comment by Thamos** [comment]
@Daedra223 How come the sudden change of opinion?

**Comment by Daedra223** [comment]
@Thamos thinking about the aim of jodel to create an original repostfree community, that I dont want to destroy ... so thats why we should stop publicate the keyd and better communicate them within a small group of person. Nevertheless the more knowing them the faster jodel finds a way to change it ... so to keep that working just send it privatelly to certain ppl

**Comment by aschaeufler** [comment]
So basicly the keys should be shared just with you?😂

Am 20.08.2017 23:28 schrieb "Daedra223" <notifications@github.com>:

**Comment by Daedra223** [comment]
@aschaeufler I didnt say that I belong to this small group of person who should get the key. To protect the community I would rather prefer to not get it than to let everyone have it ... so jodel becomes a massive reposting platform ...

**Comment by andrelanger** [comment]
it seems like the api key has changed again...

jodel-api v1.2.10

>>> j = jodel_api.JodelAccount(lat=lat, lng=lng, city=city)
Creating new account.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/jodel_api/jodel_api.py", line 56,    in __init__
    r = self.refresh_all_tokens(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jodel_api/jodel_api.py", line 136   , in refresh_all_tokens
    raise Exception(resp)
Exception: (477, {u'metadata': None, u'error': u'Signed request expected'})

**Comment by petrekova** [comment]
@andrelanger take a look at [this Repo](https://bitbucket.org/cfib90/ojoc-keyhack/src/1c5ba2699279e84bac7d30157120844d7edcc9ef/x86/?at=public) to generate your own key.

Note that the scripts are somewhat broken. E.g. `download_apk.sh` doesn't work anymore(because the apk provider probably changed the way it provides the apk). So you'll have to either fix the script(see [this file](https://github.com/nborrmann/jodeldecompile/blob/master/tools/googleplay-api/jodeldl.py) of @nborrmann )or you'll have to manually download the newest apk and then point to it in `decrypt.sh`.

By the way, @nborrmann, could it be that your build script is broken? I took a look at your Travis CI and it seems it has some issue with pip if I remember right. Otherwise it should push the newest version with the signed keys automatically, shouldn't it?

**Comment by nborrmann** [comment]
@petrekova Yeah, that's a bit broken. But it does publish the newest version on PyPI, the issue is that it fails if the current version already exists on PyPI. Previously it just failed silently, now it crashes the build. I was too lazy to fix it tbh.

**Comment by nknappe** [comment]
Signing key changed again with v4.80.5

**Comment by cartman4** [comment]
Version 4.80.5 seems to be: KmzWCGdpAnxWWTyiTzVCBhXCfSxCgEAAmzvsOGjI

**Comment by m7ariri** [comment]
4.80.5 signing key?

**Comment by nknappe** [comment]
@m7ariri 
4.80.5 is outdated

**Comment by deucalion** [comment]
This bug looks like a prime candidate for "wontfix"... 😏😉

**Comment by guitar9** [comment]
when does the new version comes out? get errot 477

**Comment by xH2Osecond** [comment]
I found this key from the apk manually `swbBCdBLdtvSqgflkjyrXXXXXXXXXXXXXXXXXXXX` but it doesn't work. Can someone confirm that is the key or this API not working (447 error)?

**Comment by UMTti** [comment]
@nborrmann @ioncodes Do you know is there now any working way to retrieve signing key? Or can you update this pip package to work?

**Comment by ioncodes** [comment]
@UMTti I have the keys but I'm not allowed to share them anymore :/

**Comment by deucalion** [comment]
What's so hard to understand?

The entire point is to make it not too easy for amateurs to use this so Jodel won't get flooded with spam and Jodel HQ won't implement further measures to bar others from using their platform.

One user in this thread already has been kind enough to share a tool to allow extraction of a new key; if you are unable to use it, either improve your skill level or leave the rest of us here alone... PLEASE.

@nborrmann please close this bug and mark it as wontfix.

**Comment by ioncodes** [comment]
Tbh, the tool didn't work anymore at some point. I had to make my own, are you sure it actually works for you?

**Comment by deucalion** [comment]
Only with a few adaptations, admittedly. But if you're familiar enough with the tooling, I wouldn't consider that a real issue.

**Comment by ioncodes** [comment]
Well I'm not really familiar with it since I have my own tool xD I don't like relying on other people too much
