### ISSUE TITLE
Got error 477

### ISSUE THREAD

**Issue by aurelebonvin** [nborrmann/jodel_api#71]
## Issue

I tested to write the code of example with my data, and as soon as I start the script, I get the error 477. Here is the traceback:
```
PS E:\JodelApi> py .\jodel_list.py
Creating new account.
Traceback (most recent call last):  File ".\jodel_list.py", line 4, in <module>
    j = jodel_api.JodelAccount(lat=lat, lng=lng, city=city)  File "C:\Users\[...]\AppData\Local\Programs\Python\Python36-32\lib\site-packages\jodel_api\jodel_api.py", line 56, in __init__
    r = self.refresh_all_tokens(**kwargs)  File "C:\Users\[...]\AppData\Local\Programs\Python\Python36-32\lib\site-packages\jodel_api\jodel_api.py", line 136, in refresh_all_tokens
    raise Exception(resp)
Exception: (477, {'error': 'Signed request expected', 'metadata': None})
```

And here is my code
```
import jodel_api

lat, lng, city = [...], [...], "Somewhere in Switzerland"
j = jodel_api.JodelAccount(lat=lat, lng=lng, city=city)

j.get_account_data()
```

## Environment

If you're reporting a bug, please attach the output of the following commands:

```
$ pip show jodel_api
Name: jodel-api
Version: 1.2.11
Summary: Unoffical Python Interface to the Jodel API
Home-page: https://github.com/nborrmann/jodel_api
Author: Nils Borrmann
Author-email: n.borrmann@googlemail.com
License: MIT
Location: c:\users\[...]\appdata\local\programs\python\python36-32\lib\site-packages
Requires: varint, protobuf, future, mock, requests
Required-by:

$ pip -V
pip 10.0.1 from c:\[...]\python\python36-32\lib\site-packages\pip (python 3.6)

$ python -V
Python 3.6.5

$ python -c "import jodel_api; print(jodel_api.JodelAccount.version); print(jodel_api.JodelAccount.secret)"
4.79.1
b'HtJoqSysGFQXgFqYZRgwbpcFVAzLFSioVKTCwMcL'
```

**Comment by adgehrke** [comment]
I always get the same error since a few weeks
