### ISSUE TITLE
signing key

### ISSUE THREAD

**Issue by KoenBremer** [nborrmann/jodel_api#76]
## Issue
The signing key is not correct, while being on the latest version of the api..
...

## Environment

If you're reporting a bug, please attach the output of the following commands:

```
$ pip show jodel_api
$ pip -V
$ python -V
$ python -c "import jodel_api; print(jodel_api.JodelAccount.version); print(jodel_api.JodelAccount.secret)"
```

**Comment by leon1995** [comment]
I get the same issue:
```
lat, lng, city = 48.148434, 11.567867, "Munich"`
j = jodel_api.JodelAccount(lat=lat, lng=lng, city=city)
Creating new account.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leon/.local/lib/python3.5/site-packages/jodel_api/jodel_api.py", line 56, in __init__
    r = self.refresh_all_tokens(**kwargs)
  File "/home/leon/.local/lib/python3.5/site-packages/jodel_api/jodel_api.py", line 136, in refresh_all_tokens
    raise Exception(resp)
Exception: (477, {'error': 'Signed request expected', 'metadata': None})
```

**Environment**
```
$ pip show jodel_api
Name: jodel-api
Version: 1.2.11
Summary: Unoffical Python Interface to the Jodel API
Home-page: https://github.com/nborrmann/jodel_api
Author: Nils Borrmann
Author-email: n.borrmann@googlemail.com
License: MIT
Location: /home/leon/.local/lib/python3.5/site-packages
Requires: mock, varint, requests, protobuf, future
Required-by:
```
```
$ pip -V
pip 10.0.1 from /home/user /.local/lib/python3.5/site-packages/pip (python 3.5)
```
```
$ python3 -V
Python 3.5.2
```
```
$ python3 -c "import jodel_api; print(jodel_api.JodelAccount.version); print(jodel_api.JodelAccount.secret)"
4.79.1
b'HtJoqSysGFQXgFqYZRgwbpcFVAzLFSioVKTCwMcL'
```
