### ISSUE TITLE
Host is down

### ISSUE THREAD

**Issue by jacopo-j** [nborrmann/jodel_api#79]
Since several days, `jodel_api` (current version) cannot connect to Jodel's servers at all. This is *not* a signing issue, and not even an authorization problem. Trying on different machines, with different IP addresses and from different locations always leads to the same result:

```python
>>> import jodel_api
>>> lat = XX.XXXXXX
>>> lon = XX.XXXXXX
>>> j = jodel_api.JodelAccount(lat=lat, lng=lon, city="XXXXXX")
Creating new account.

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jodel_api/jodel_api.py", line 56, in __init__
    r = self.refresh_all_tokens(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jodel_api/jodel_api.py", line 129, in refresh_all_tokens
    resp = self._send_request("POST", "/v2/users", payload=payload, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jodel_api/jodel_api.py", line 69, in _send_request
    resp = s.request(method=method, url=url, params=params, json=payload, headers=headers, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.go-tellm.com', port=443): Max retries exceeded with url: /api/v2/users (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x104ab5198>: Failed to establish a new connection: [Errno 64] Host is down',))
HTTPSConnectionPool(host='api.go-tellm.com', port=443): Max retries exceeded with url: /api/v2/users (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x104ab5198>: Failed to establish a new connection: [Errno 64] Host is down',))
```

Has anybody experinced the same (weird) problem?

**Comment by jacopo-j** [comment]
Problem was related to my setup.
