### ISSUE TITLE
Can't create an account

### ISSUE THREAD

**Issue by Taegos** [nborrmann/jodel_api#82]
Just cloned this and tried to create an account: 

```
import jodel_api
lat, lng, city = 48.148434, 11.567867, "Munich"
j = jodel_api.JodelAccount(lat=lat, lng=lng, city=city)
```

But got:
```
Traceback (most recent call last):
  File ".\notifier.py", line 3, in <module>
    j = jodel_api.JodelAccount(lat=lat, lng=lng, city=city)
  File "C:\Users\Benjamin\Desktop\JodelNotifier\venv\lib\site-packages\jodel_api\jodel_api.py", line 56, in __init__
    r = self.refresh_all_tokens(**kwargs)
  File "C:\Users\Benjamin\Desktop\JodelNotifier\venv\lib\site-packages\jodel_api\jodel_api.py", line 136, in refresh_all_tokens
    raise Exception(resp)
Exception: (477, {'error': 'Signed request expected', 'metadata': None})
```

According to the readme i should  

> Make sure to upgrade to the latest version of jodel_api, as the signing key changes every few weeks.

I just cloned the repo so i should have the latest version, right? 

Anyone seeing similar problems?

**Comment by jacopo-j** [comment]
This repo won't likely be updated with the latest signing key anymore, see #39 and #40. Besides, this is just another duplicate of #71 and #76.

**Comment by Taegos** [comment]
Yeah saw that now, should probably be in the readme

**Comment by Benjamin-3281** [comment]
Can anybody hint in which direction to work towards to get the signing key? :) 
I have a jodel-related uni project and would spend weeks of manual labour if I can't get it to work again, so im ready to try out some trickier options
