### ISSUE TITLE
Is there any plan to update the keys?

### ISSUE THREAD

**Issue by gaardhus** [nborrmann/jodel_api#85]
I'm getting errors on the keys, and I don't know how to find the updated signing versions. Is there a plan to update the files, or can anybody point me in the direction on how to update them manually?

When I'm running
`j = jodel_api.JodelAccount(lat=lat, lng=lng, city=city)`

I get the following output:
```
Creating new account.
Traceback (most recent call last):

  File "<ipython-input-77-1a5f3f511db7>", line 1, in <module>
    j = jodel_api.JodelAccount(lat=lat, lng=lng, city=city)

  File "C:\Users\tobia\Anaconda3\lib\site-packages\jodel_api\jodel_api.py", line 56, in __init__
    r = self.refresh_all_tokens(**kwargs)

  File "C:\Users\tobia\Anaconda3\lib\site-packages\jodel_api\jodel_api.py", line 136, in refresh_all_tokens
    raise Exception(resp)

Exception: (477, {'error': 'Signed request expected', 'metadata': None})
```

**Comment by datagutten** [comment]
I was able to extract a key, but the API would not accept it.

**Comment by guitar9** [comment]
I think this project is outdated :D Somebody has another solution to get Jodel Posts programmatically?

**Comment by gaardhus** [comment]
@guitar9 yeah you are probably right. If you stumble upon a useful method please update me :).

**Comment by marbink** [comment]
if you are able to get the key from ios & update version, my fork would work ;)
